import Head from "next/head"
import { Button, Container } from "@chakra-ui/react"
import { chunk } from "../lib/helper/lodash-alt"
import DatabaseService from "../lib/services/database.services"
import { user } from "../../database/user"
import { User, Video, YoutubeChannel } from "@prisma/client"
import { channels } from "../../database/channels"
import { videos } from "../../database/videos"

// TODO
// Add IA official

export default function Home(props) {
  const database = new DatabaseService()

  const generateUser = async () => {
    const users: User[] = user.map((item) => {
      return {
        ...item,
        isActive: item.isActive === 1,
        createdDate: new Date(item.createdDate),
        createdAt: new Date(item.createdAt),
        deletedAt: null
      }
    })

    const chunked = chunk(users, 1000)

    for (const c of chunked) {
      await database.initUser(c)
    }
  }

  const generateChannel = async () => {
    const chs: YoutubeChannel[] = channels.map((item) => {
      return {
        ...item,
        createdAt: new Date(item.createdAt),
        insertAt: new Date(item.insertAt),
        deletedAt: null,
        included: item.included === 1
      }
    })

    const chunked = chunk(chs, 1000)

    for (const c of chunked) {
      await database.initChannels(c)
    }
  }

  const generateVideo = async () => {
    const vds: Video[] = videos.map((item) => {
      return {
        ...item,
        createdAt: new Date(item.createdAt),
        uploadDate: new Date(item.uploadDate),
        deletedAt: null,
        show: item.show === 1
      }
    })

    const chunked = chunk(vds, 1000)

    for (const c of chunked) {
      await database.initVideos(c)
    }
  }

  return (
    <>
      <Head>
        <title>Sandbox Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.lg">
        <Button colorScheme="teal" onClick={generateUser}>
          Generate User
        </Button>
        <Button colorScheme="teal" onClick={generateChannel}>
          Generate Channel
        </Button>
        <Button colorScheme="teal" onClick={generateVideo}>
          Generate Video
        </Button>
      </Container>

      {/* <pre>
        <pre>{JSON.stringify(videos, null, 2)}</pre>
      </pre> */}
    </>
  )
}
