import { DeleteIcon, LinkIcon } from "@chakra-ui/icons"
import { Button, Container } from "@chakra-ui/react"
import exportFromJSON from "export-from-json"
import Head from "next/head"
import React, { useEffect, useState } from "react"
import { RAW_JUL_24_CHART } from "../database/jul_24"
import PrismaService from "../lib/services/prisma.service"
import { RawChart } from "../types/ui"

const DataChecking = (props) => {
  const [videos, setVideos] = useState<RawChart[]>([])

  const prisma = new PrismaService()

  useEffect(() => {
    setVideos(RAW_JUL_24_CHART)
  }, [])

  const convertToJson = () => {
    exportFromJSON({ data: videos, fileName: "all_chart_jul_3", exportType: "json" })
  }

  const removeVideo = (index: number, id: string) => async () => {
    const video = [...videos]
    video.splice(index, 1)

    await prisma.ignoreVideo(id)

    setVideos(video)
  }

  const goToVideo = (link: string) => () => {
    window.open(`https://www.youtube.com/watch?v=${link}`)
  }

  return (
    <>
      <Head>
        <title>Data Checking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="container.lg" className="raw-chart">
        <Button onClick={convertToJson} className="m-10">
          Convert
        </Button>

        {videos.map((item, i) => (
          <div key={i} className="raw-chart__card">
            <div>{i + 1}</div>
            <img src={item.thumbnail} alt="" />
            <div className="raw-chart__card__body">
              <div className="raw-chart__card__body__title">{item.videoTitle}</div>
              <div className="raw-chart__card__body__artist">{item.channelName}</div>
            </div>
            <div className="raw-chart__card__handler">
              <Button onClick={removeVideo(i, item.id)}>
                <DeleteIcon />
              </Button>
              <Button onClick={goToVideo(item.id)}>
                <LinkIcon />
              </Button>
              <div>{item.id}</div>
            </div>
          </div>
        ))}
      </Container>
    </>
  )
}

export default DataChecking
