import { Box, Container } from "@chakra-ui/react"
import Head from "next/head"
import { useEffect, useState } from "react"
import PrismaService from "../lib/services/prisma.service"
import { Chart, ChartDetail } from "../types/ui"
import { ChartComponent } from "../components/chart-component"

// TODO
// Add IA official

export default function Home(props) {
  const [videos, setVideos] = useState<ChartDetail[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [videoLinks, setVideoLinks] = useState([])

  const prisma = new PrismaService()

  useEffect(() => {
    const getData = async () => {
      const res = await prisma.getCurrentChart(6)

      if (res.isSuccess) {
        const data = res.getValue()
        setVideos(data)
        console.log(data)
      }

      setIsLoading(false)
    }

    getData()
  }, [])

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="home-chart">
        <Container maxWidth="container.xl">
          <div className="home-chart__header">
            <img src="/hiiiru.jpg" alt="" />
            <div className="home-chart__header__title">
              <h1>Vocaloid/UTAU/Synth Chart</h1>
              <h3>Original Edition</h3>
              <h5>Per Aug 7, 2021</h5>
            </div>
            <div className="home-chart__header__week">
              <div className="home-chart__header__week__title">Week</div>
              <div className="home-chart__header__week__number">1</div>
              <div className="home-chart__header__week__year">2021</div>
            </div>
          </div>

          <Box>
            {videos.slice(0, 20).map((item, i) => (
              <ChartComponent video={item} index={i} indexAdd={1} key={i} type="all" />
            ))}
          </Box>
        </Container>
      </Box>
    </>
  )
}
