import Head from "next/head"
import { Button, Container } from "@chakra-ui/react"

import InitService from "../lib/services/init.service"
import PrismaService from "../lib/services/prisma.service"
import { chunk } from "../lib/helper/lodash-alt"
import exportFromJSON from "export-from-json"
import ChartHelper from "../lib/helper/chart"
import { STATISTIC_WEEK_3 } from "../../database/statistic/statistic_week_3"
import { NEW_JUL_17_CHART } from "../database/jul_17"

// TODO
// Add IA official

export default function Home(props) {
  const init = new InitService()
  const prisma = new PrismaService()
  const helper = new ChartHelper()

  const generateVideos = async () => {
    try {
      const res = await prisma.getChannels()

      if (res.isSuccess) {
        const data = res.getValue()

        await init.initChannelVideos(data)
      }
    } catch (error) {
      console.log(error)
    }
  }

  const generateStatistic = async () => {
    try {
      const res = await prisma.getVideos()

      if (res.isSuccess) {
        const data = res.getValue()

        const chunked = chunk(data, 50)

        // const res = await init.initStatistic(chunked[0], 0)

        // console.log(res.isSuccess)

        let index = 0

        while (index < chunked.length) {
          await init.initStatistic(chunked[index], 2)
          index++
        }
      }
    } catch (error) {
      console.log(error)
    }
  }

  const generateChart = async () => {
    const res = await prisma.getStatistic()

    if (res.isSuccess) {
      const data = res.getValue()
      console.log(data)
      const array = []

      for (let index = 0; index < data.length; index++) {
        const element = data[index]

        const obj = helper.chartMaker(element, STATISTIC_WEEK_3, element.video)
        array.push(obj)
      }

      exportFromJSON({ data: array, fileName: "chart_jul_24", exportType: "csv" })
      exportFromJSON({ data: array, fileName: "chart_jul_24", exportType: "json" })

      return array
    } else {
      console.log("object")
    }
  }

  const openAllVideo = () => {
    for (const video of NEW_JUL_17_CHART) {
      window.open(`https://www.youtube.com/watch?v=${video.id}`, "_blank")
      console.log(video.id)
    }
  }

  return (
    <>
      <Head>
        <title>Sandbox Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.lg">
        <Button colorScheme="teal" onClick={generateVideos}>
          Generate Video
        </Button>
        <Button colorScheme="teal" onClick={generateStatistic}>
          Generate Statistic
        </Button>
        <Button colorScheme="teal" onClick={generateChart}>
          Generate Chart
        </Button>
        <Button colorScheme="teal" onClick={openAllVideo}>
          Open all video
        </Button>
      </Container>

      {/* <pre>
        <pre>{JSON.stringify(videos, null, 2)}</pre>
      </pre> */}
    </>
  )
}
