import { Box, Container } from "@chakra-ui/react"
import Head from "next/head"
import { useEffect, useState } from "react"
import PrismaService from "../../lib/services/prisma.service"
import { Chart, ChartDetail } from "../../types/ui"
import { ChartComponent } from "../../components/chart-component"
import { KAFU_AUG_7 } from "../../database/kafu/aug_7"
import { KAFU_WEEK_1 } from "../../database/kafu/week_1"

// TODO
// Add IA official

export default function Home(props) {
  const [videos, setVideos] = useState<ChartDetail[]>([])
  const [isLoading, setIsLoading] = useState(true)

  const prisma = new PrismaService()

  useEffect(() => {
    const getData = async () => {
      const res = await prisma.getKafuCurrentChart(1)

      if (res.isSuccess) {
        const data = res.getValue()
        setVideos(data)
        console.log(data)
      }

      setIsLoading(false)
    }

    getData()
  }, [])

  return (
    <>
      <Head>
        <title>KAFU Chart - hiiru edition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="home-chart home-chart--kafu">
        <Container maxWidth="container.xl">
          <div className="home-chart__header">
            <img src="/unnamed.jpg" alt="" />
            <div className="home-chart__header__title">
              <h1>KAFU Chart</h1>
              <h3>hiiru Edition</h3>
              <h5>Per August 7, 2021</h5>
            </div>
            <div className="home-chart__header__week">
              <div className="home-chart__header__week__title">Week</div>
              <div className="home-chart__header__week__number">1</div>
              <div className="home-chart__header__week__year">2021</div>
            </div>
          </div>

          <Box>
            {videos.slice(0, 20).map((item, i) => (
              <ChartComponent video={item} index={i} indexAdd={1} key={i} type="all" />
            ))}
          </Box>
        </Container>
      </Box>
    </>
  )
}
