import { Box, Container } from "@chakra-ui/react"
import Head from "next/head"
import { useEffect, useState } from "react"
import PrismaService from "../../lib/services/prisma.service"
import { Chart } from "../../types/ui"
import { ChartComponent } from "../../components/chart-component"
import { KAFU_AUG_7 } from "../../database/kafu/aug_7"

// TODO
// Add IA official

export default function Home(props) {
  const [videos, setVideos] = useState<Chart[]>([])
  const [isLoading, setIsLoading] = useState(true)

  const prisma = new PrismaService()

  useEffect(() => {
    const getData = async () => {
      const array: Chart[] = []
      const links = []

      for (let index = KAFU_AUG_7.length - 1; index >= 0; index--) {
        const element = KAFU_AUG_7[index]

        const res = await prisma.getVideo(element.id)
        if (res.isSuccess) {
          const data = res.getValue()

          if (data) {
            // @ts-ignore
            array.push({
              ...data,
              isNew: element.isNew,
              bestPosition: index,
              lastWeek: element.lastWeek ?? KAFU_AUG_7.length - index,
              weeksInChart: 1,
              score: 0,
              views: element.views
            })
          }
        }
      }

      setVideos(array)
      setIsLoading(false)
    }

    getData()
  }, [])

  return (
    <>
      <Head>
        <title>KAFU Most Viewed Chart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className="home-chart home-chart--kafu">
        <Container maxWidth="container.xl">
          <div className="home-chart__header">
            <img src="/unnamed.jpg" alt="" />
            <div className="home-chart__header__title">
              <h1>KAFU Chart</h1>
              <h3>Most Viewed Edition</h3>
              <h5>Per August 7, 2021</h5>
            </div>
            <div className="home-chart__header__week">
              <div className="home-chart__header__week__title">Week</div>
              <div className="home-chart__header__week__number">6</div>
              <div className="home-chart__header__week__year">2021</div>
            </div>
          </div>

          <Box>
            {videos.slice(0, 10).map((item, i) => (
              <ChartComponent video={item} index={i} indexAdd={1} key={i} type="new" isKafu />
            ))}
          </Box>
        </Container>
      </Box>
    </>
  )
}
